package com.jagapathi.pharmacy.notification.domain;

public enum NotificationType {
    ORDER_CONFIRMATION,
    ORDER_SHIPPED,
    PAYMENT_FAILED,
    PRESCRIPTION_VERIFIED,
    PRESCRIPTION_REJECTED,
    PRESCRIPTION_FILLED,
    PRESCRIPTION_EXPIRING,
    REFUND_PROCESSED,
    STOCK_ALERT
}
