spring:
  application:
    name: audit-service
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: false
  datasource:
    url: jdbc:h2:mem:audit_test;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=false
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  kafka:
    bootstrap-servers: localhost:9092
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
  cache:
    type: simple
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081
          jwk-set-uri: http://localhost:8081/.well-known/jwks.json
  flyway:
    enabled: false

server:
  port: 8086

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
