apiVersion: v1
kind: ConfigMap
metadata:
  name: pharmacy-common
  namespace: pharmacy
data:
  REDIS_HOST: redis
  REDIS_PORT: "6379"
  KAFKA_BOOTSTRAP_SERVERS: host.docker.internal:9092
  AUTH_SERVICE_HOST: auth-service
  AUTH_SERVICE_PORT: "8081"
  DB_HOST: host.docker.internal
  DB_PORT: "3306"
  PRODUCT_SERVICE_PORT: "8081"
  CUSTOMER_DB_NAME: pharmacy_customer
  CUSTOMER_DB_USER: customer_user
  PHARMACY_DB_NAME: pharmacy_pharmacy
  PHARMACY_DB_USER: pharmacy_user
  AUTH_DB_NAME: auth_service
  AUTH_DB_USER: auth_user
  PRODUCT_DB_NAME: pharmacy_product
  PRODUCT_DB_USER: product_user
