apiVersion: v1
kind: Secret
metadata:
  name: pharmacy-secrets
  namespace: pharmacy
type: Opaque
stringData:
  DB_PASSWORD: change-me
  JWT_PRIVATE_KEY_PEM: change-me
  AUTH_DB_PASSWORD: auth_password
  CUSTOMER_DB_PASSWORD: password
  PHARMACY_DB_PASSWORD: password
  PRODUCT_DB_PASSWORD: product_password
