CREATE DATABASE IF NOT EXISTS auth_service;
CREATE DATABASE IF NOT EXISTS pharmacy_product;
CREATE DATABASE IF NOT EXISTS pharmacy_inventory;
CREATE DATABASE IF NOT EXISTS pharmacy_order;
CREATE DATABASE IF NOT EXISTS pharmacy_payment;
CREATE DATABASE IF NOT EXISTS pharmacy_audit;
CREATE DATABASE IF NOT EXISTS pharmacy_customer;
CREATE DATABASE IF NOT EXISTS pharmacy_pharmacy;
CREATE DATABASE IF NOT EXISTS prescription_service;
CREATE DATABASE IF NOT EXISTS pharmacy_notification;

CREATE USER IF NOT EXISTS 'auth_user'@'%' IDENTIFIED BY 'auth_password';
CREATE USER IF NOT EXISTS 'auth_user'@'localhost' IDENTIFIED BY 'auth_password';
CREATE USER IF NOT EXISTS 'product_user'@'%' IDENTIFIED BY 'product_password';
CREATE USER IF NOT EXISTS 'product_user'@'localhost' IDENTIFIED BY 'product_password';
CREATE USER IF NOT EXISTS 'inventory_user'@'%' IDENTIFIED BY 'inventory_password';
CREATE USER IF NOT EXISTS 'inventory_user'@'localhost' IDENTIFIED BY 'inventory_password';
CREATE USER IF NOT EXISTS 'order_user'@'%' IDENTIFIED BY 'order_password';
CREATE USER IF NOT EXISTS 'order_user'@'localhost' IDENTIFIED BY 'order_password';
CREATE USER IF NOT EXISTS 'payment_user'@'%' IDENTIFIED BY 'payment_password';
CREATE USER IF NOT EXISTS 'payment_user'@'localhost' IDENTIFIED BY 'payment_password';
CREATE USER IF NOT EXISTS 'audit_user'@'%' IDENTIFIED BY 'audit_password';
CREATE USER IF NOT EXISTS 'audit_user'@'localhost' IDENTIFIED BY 'audit_password';
CREATE USER IF NOT EXISTS 'customer_user'@'%' IDENTIFIED BY 'password';
CREATE USER IF NOT EXISTS 'customer_user'@'localhost' IDENTIFIED BY 'password';
CREATE USER IF NOT EXISTS 'pharmacy_user'@'%' IDENTIFIED BY 'password';
CREATE USER IF NOT EXISTS 'pharmacy_user'@'localhost' IDENTIFIED BY 'password';
CREATE USER IF NOT EXISTS 'prescription_user'@'%' IDENTIFIED BY 'prescription_password';
CREATE USER IF NOT EXISTS 'prescription_user'@'localhost' IDENTIFIED BY 'prescription_password';
CREATE USER IF NOT EXISTS 'pharmacy_notification'@'%' IDENTIFIED BY 'pharmacy_notification';
CREATE USER IF NOT EXISTS 'pharmacy_notification'@'localhost' IDENTIFIED BY 'pharmacy_notification';

GRANT ALL PRIVILEGES ON auth_service.* TO 'auth_user'@'%';
GRANT ALL PRIVILEGES ON auth_service.* TO 'auth_user'@'localhost';
GRANT ALL PRIVILEGES ON pharmacy_product.* TO 'product_user'@'%';
GRANT ALL PRIVILEGES ON pharmacy_product.* TO 'product_user'@'localhost';
GRANT ALL PRIVILEGES ON pharmacy_inventory.* TO 'inventory_user'@'%';
GRANT ALL PRIVILEGES ON pharmacy_inventory.* TO 'inventory_user'@'localhost';
GRANT ALL PRIVILEGES ON pharmacy_order.* TO 'order_user'@'%';
GRANT ALL PRIVILEGES ON pharmacy_order.* TO 'order_user'@'localhost';
GRANT ALL PRIVILEGES ON pharmacy_payment.* TO 'payment_user'@'%';
GRANT ALL PRIVILEGES ON pharmacy_payment.* TO 'payment_user'@'localhost';
GRANT ALL PRIVILEGES ON pharmacy_audit.* TO 'audit_user'@'%';
GRANT ALL PRIVILEGES ON pharmacy_audit.* TO 'audit_user'@'localhost';
GRANT ALL PRIVILEGES ON pharmacy_customer.* TO 'customer_user'@'%';
GRANT ALL PRIVILEGES ON pharmacy_customer.* TO 'customer_user'@'localhost';
GRANT ALL PRIVILEGES ON pharmacy_pharmacy.* TO 'pharmacy_user'@'%';
GRANT ALL PRIVILEGES ON pharmacy_pharmacy.* TO 'pharmacy_user'@'localhost';
GRANT ALL PRIVILEGES ON prescription_service.* TO 'prescription_user'@'%';
GRANT ALL PRIVILEGES ON prescription_service.* TO 'prescription_user'@'localhost';
GRANT ALL PRIVILEGES ON pharmacy_notification.* TO 'pharmacy_notification'@'%';
GRANT ALL PRIVILEGES ON pharmacy_notification.* TO 'pharmacy_notification'@'localhost';
FLUSH PRIVILEGES;
