terraform {
  required_version = ">= 1.9, < 2.0"

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.70"
    }
    # The random and tls providers are deliberately absent. Their resources
    # (random_password, tls_private_key) store generated values in plaintext in
    # Terraform state, which is exactly what this environment avoids. Secrets
    # are generated by scripts/aws-seed-secrets.sh instead. Re-adding them
    # would reintroduce credentials into the versioned state bucket.
  }
}
