apiVersion: apps/v1
kind: Deployment
metadata:
  name: prescription-service
  namespace: pharmacy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prescription-service
  template:
    metadata:
      labels:
        app: prescription-service
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 10001
        runAsGroup: 10001
        fsGroup: 10001
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: prescription-service
          image: pharmacy/prescription-service:local
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: ["ALL"]
          volumeMounts:
            - name: tmp
              mountPath: /tmp
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8086
          envFrom:
            - configMapRef:
                name: pharmacy-common
          env:
            - name: DB_HOST
              value: host.docker.internal
            - name: DB_NAME
              value: prescription_service
            - name: DB_USER
              value: prescription_user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pharmacy-secrets
                  key: PRESCRIPTION_DB_PASSWORD
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8086
            initialDelaySeconds: 20
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8086
            initialDelaySeconds: 30
            periodSeconds: 15
      volumes:
        - name: tmp
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: prescription-service
  namespace: pharmacy
spec:
  selector:
    app: prescription-service
  ports:
    - port: 8086
      targetPort: 8086
  type: ClusterIP
