terraform {
  required_version = ">= 1.9, < 2.0"
}

variable "name_prefix" {
  type = string
}

variable "tags" {
  type    = map(string)
  default = {}
}

# Random passwords generated by Terraform, never hardcoded/committed.
resource "random_password" "auth_db" {
  length  = 24
  special = false
}

resource "random_password" "product_db" {
  length  = 24
  special = false
}

resource "aws_secretsmanager_secret" "auth_db" {
  name                    = "${var.name_prefix}/auth-service/db-credentials"
  recovery_window_in_days = 0 # immediate delete on destroy — temporary exercise, no production data
  tags                    = var.tags
}

resource "aws_secretsmanager_secret_version" "auth_db" {
  secret_id = aws_secretsmanager_secret.auth_db.id
  secret_string = jsonencode({
    username = "auth_user"
    password = random_password.auth_db.result
  })
}

resource "aws_secretsmanager_secret" "product_db" {
  name                    = "${var.name_prefix}/product-service/db-credentials"
  recovery_window_in_days = 0
  tags                    = var.tags
}

resource "aws_secretsmanager_secret_version" "product_db" {
  secret_id = aws_secretsmanager_secret.product_db.id
  secret_string = jsonencode({
    username = "product_user"
    password = random_password.product_db.result
  })
}

# RSA keypair for JWT signing, generated by Terraform (tls provider) so the
# private key never appears in a file on disk outside of state, and state
# itself lives encrypted in the S3 remote backend (see envs/sandbox/backend.tf).
resource "tls_private_key" "jwt" {
  algorithm = "RSA"
  rsa_bits  = 2048
}

resource "aws_secretsmanager_secret" "jwt_keypair" {
  name                    = "${var.name_prefix}/auth-service/jwt-keypair"
  recovery_window_in_days = 0
  tags                    = var.tags
}

resource "aws_secretsmanager_secret_version" "jwt_keypair" {
  secret_id = aws_secretsmanager_secret.jwt_keypair.id
  secret_string = jsonencode({
    # auth-service's JwtProvider expects PKCS8 ("-----BEGIN PRIVATE KEY-----"),
    # not the default PKCS1 ("-----BEGIN RSA PRIVATE KEY-----") that
    # tls_private_key.private_key_pem emits.
    private_key_pem = tls_private_key.jwt.private_key_pem_pkcs8
    public_key_pem  = tls_private_key.jwt.public_key_pem
  })
}

output "auth_db_secret_arn" {
  value = aws_secretsmanager_secret.auth_db.arn
}

output "product_db_secret_arn" {
  value = aws_secretsmanager_secret.product_db.arn
}

output "jwt_keypair_secret_arn" {
  value = aws_secretsmanager_secret.jwt_keypair.arn
}

output "auth_db_password" {
  value     = random_password.auth_db.result
  sensitive = true
}

output "product_db_password" {
  value     = random_password.product_db.result
  sensitive = true
}
