apiVersion: v1
kind: Namespace
metadata:
  name: pharmacy
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: db-bootstrap
  namespace: pharmacy
  annotations:
    eks.amazonaws.com/role-arn: __DB_BOOTSTRAP_ROLE_ARN__
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: api-gateway
  namespace: pharmacy
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: auth-service
  namespace: pharmacy
  annotations:
    eks.amazonaws.com/role-arn: __AUTH_SERVICE_ROLE_ARN__
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: product-service
  namespace: pharmacy
  annotations:
    eks.amazonaws.com/role-arn: __PRODUCT_SERVICE_ROLE_ARN__
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: customer-service
  namespace: pharmacy
  annotations:
    eks.amazonaws.com/role-arn: __CUSTOMER_SERVICE_ROLE_ARN__
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pharmacy-service
  namespace: pharmacy
  annotations:
    eks.amazonaws.com/role-arn: __PHARMACY_SERVICE_ROLE_ARN__
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: inventory-service
  namespace: pharmacy
  annotations:
    eks.amazonaws.com/role-arn: __INVENTORY_SERVICE_ROLE_ARN__
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prescription-service
  namespace: pharmacy
  annotations:
    eks.amazonaws.com/role-arn: __PRESCRIPTION_SERVICE_ROLE_ARN__
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: order-service
  namespace: pharmacy
  annotations:
    eks.amazonaws.com/role-arn: __ORDER_SERVICE_ROLE_ARN__
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: payment-service
  namespace: pharmacy
  annotations:
    eks.amazonaws.com/role-arn: __PAYMENT_SERVICE_ROLE_ARN__
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: notification-service
  namespace: pharmacy
  annotations:
    eks.amazonaws.com/role-arn: __NOTIFICATION_SERVICE_ROLE_ARN__
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: audit-service
  namespace: pharmacy
  annotations:
    eks.amazonaws.com/role-arn: __AUDIT_SERVICE_ROLE_ARN__
