namespace: pharmacy
commonConfig:
  REDIS_HOST: redis
  REDIS_PORT: "6379"
  KAFKA_BOOTSTRAP_SERVERS: kafka:9092
  AUTH_SERVICE_HOST: auth-service
  AUTH_SERVICE_PORT: "8081"
services:
  api-gateway:
    image: pharmacy/api-gateway:1.0.0
    port: 8080
    managementPort: 9081
  auth-service:
    image: pharmacy/auth-service:1.0.0
    port: 8081
  product-service:
    image: pharmacy/product-service:1.0.0
    port: 8081
